#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define OLED_TIMEOUT 0
#define OLED_UPDATE_INTERVAL 50
#define OLED_BRIGHTNESS 120
#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_HUE 170
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 96
